# This is used to generate istio.yaml for minimal, demo mode.
# It is shipped with the release, used for bookinfo or quick installation of istio.
# Includes components used in the demo, defaults to alpha3 rules.
global:
  proxy:
    accessLogFile: "/dev/stdout"

  disablePolicyChecks: false

pilot:
  traceSampling: 100.0

mixer:
  adapters:
    stdio:
      enabled: true
 
grafana:
  enabled: true

tracing:
  enabled: true

servicegraph:
  enabled: true

kiali:
  enabled: true
  createDemoSecret: true

gateways:
  istio-egressgateway:
    enabled: true
