version: "1"
rules:
  - base: master
    upstream: istio:master
    autoMerge: true
    autoMergeHardReset: false
  - base: release-1.1
    upstream: istio:release-1.1
    autoMerge: true
    autoMergeHardReset: false
  - base: release-1.2
    upstream: istio:release-1.2
    autoMerge: true
    autoMergeHardReset: false
  - base: release-1.3
    upstream: istio:release-1.3
    autoMerge: true
    autoMergeHardReset: false
  - base: release-1.4
    upstream: istio:release-1.4
    autoMerge: true
    autoMergeHardReset: false
