version: 2

jobs:
  build:
    working_directory: /go/src/istio.io/istio
    docker:
      - image: gcr.io/istio-testing/istio-builder:v20191017-386873c9-dirty
    environment:
      GOPATH: /go
    steps:
      - make -e T=-v build

workflows:
  version: 2
  ci:
    jobs:
      - build
