version: 2

jobs:
  unit-tests_istio:
    machine:
      docker_layer_caching: true
    steps:
    - checkout
    - run: >-
        docker run \
          --privileged \
          -v $(pwd):/go/src/istio.io/istio/ \
          -w /go/src/istio.io/istio/ \
          -e BUILD_WITH_CONTAINER="0" \
          gcr.io/istio-testing/build-tools:master-2020-03-24T16-16-03 \
          bash -c 'make -e T=-v build racetest binaries-test'

workflows:
  version: 2
  ci:
    jobs:
      - unit-tests_istio
