version: 2

jobs:
  test:
    machine: true
    steps:
    - checkout
    - run: docker run --privileged --name build-container -v $(pwd):/go/src/istio.io/istio/ gcr.io/istio-testing/istio-builder:v20191017-386873c9-dirty
    - run: docker exec build-container bash -c 'cd /go/src/istio.io/istio/; make -e T=-v build localTestEnv test binaries-test'

workflows:
  version: 2
  ci:
    jobs:
      - test
