version: 2

defaults: &defaults
  working_directory: /go/src/istio.io/istio
  docker:
    - image: gcr.io/istio-testing/istio-builder:v20191017-386873c9-dirty
  environment:
    GOPATH: /go
    SKIP_CLEANUP: true

integrationDefaults: &integrationDefaults
  machine: true
  working_directory: /go/src/istio.io/istio
  environment:
    - CHANGE_MINIKUBE_NONE_USER: true
    - GOPATH: /go
    - SKIP_CLEANUP: true
    - KUBECONFIG: /go/out/minikube.conf
    - TEST_ENV: minikube-none

initWorkingDir: &initWorkingDir
  type: shell
  name: Initialize Working Directory
  pwd: /
  command: |
    sudo mkdir -p /go/src/istio.io/istio
    sudo chown -R circleci /go
    mkdir -p /go/out/tests
    mkdir -p /go/out/logs
    mkdir -p /home/circleci/logs

recordZeroExitCodeIfTestPassed: &recordZeroExitCodeIfTestPassed
  run:
    when: on_success
    name: Record zero exit code as test passed
    command: echo 0 > exit_code

recordNonzeroExitCodeIfTestFailed: &recordNonzeroExitCodeIfTestFailed
  run:
    when: on_fail
    name: Record nonzero exit code as test failed
    command: echo 1 > exit_code

jobs:
  build:
    <<: *defaults
    environment:
      KUBECONFIG: /go/src/istio.io/istio/.circleci/config
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: |
            mkdir -p /go/out/tests
            export PATH=$GOPATH/bin:$PATH
            make localTestEnv
            set -o pipefail
            make build T=-v
      - <<: *recordZeroExitCodeIfTestPassed
      - <<: *recordNonzeroExitCodeIfTestFailed
      - store_test_results:
          path: /go/out/tests
  test:
    <<: *integrationDefaults
    environment:
      KUBECONFIG: /go/src/istio.io/istio/.circleci/config
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: |
            mkdir -p /go/out/tests
            export PATH=$GOPATH/bin:$PATH
            make localTestEnv
            set -o pipefail
            make test binaries-test T=-v | tee -a /go/out/tests/build-log.txt
      - <<: *recordZeroExitCodeIfTestPassed
      - <<: *recordNonzeroExitCodeIfTestFailed
      - store_test_results:
          path: /go/out/tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
